#!/bin/bash
#Script to perform a reciprocal blast search
#Usage: bash runRBLAST.sh PATH/TO/QUERY/FILE PATH/TO/DB/FILE PATH/TO/OUTPUTS
#Usage ex: bash runRBLAST.sh PATH/TO/INPUT1/species1.fasta.transdecoder.pep PATH/TO/INPUT2/species2.fasta.transdecoder.pep PATH/TO/OUTPUTS

#Input query file
inputQuery="/Users/la424/Aquadro_lab/fasta_files_blast_database/GCF_000001215.4_Release_6_plus_ISO1_MT_protein_melanogaster.faa"
#Input DB reciprocal file
inputDB="/Users/la424/Aquadro_lab/fasta_files_blast_database/GCF_016746395.2_Prin_Dsim_3.1_protein.faa"

#Path to output results
outputPath="/Users/la424/Aquadro_lab/fasta_files_blast_database/blast_outputs"

#Move to query directory
queryPath=$(dirname "$inputQuery")
cd "$queryPath"
#Make blastable protein DB of the input query
makeblastdb -in "$inputQuery" -dbtype prot

#Move to DB directory
dbPath=$(dirname "$inputDB")
cd "$dbPath"
#Make blastable protein DB of the input DB
makeblastdb -in "$inputDB" -dbtype prot

#Output start status message
echo "Beginning reciprocal BLAST..."

#Move to outputs folder
cd "$outputPath"

#Use blastp to search a database
blastp -query "$inputQuery" -db "$inputDB" -max_target_seqs 1 -outfmt 6 -evalue 1e-3 -num_threads 8 > blast.outfmt6

#Switch query and search paths for reciprocal search
blastp -query "$inputDB" -db "$inputQuery" -max_target_seqs 1 -outfmt 6 -evalue 1e-3 -num_threads 8 > blast_reciprocal.outfmt6

#Output end status message
echo "Finished reciprocal BLAST!"







#!/bin/bash
#Script to filter reciprocal blast results for best hits
#Usage: bash findRBH.sh PATH/TO/QUERY/BLAST/RESULTS PATH/TO/DB/BLAST/RESULTS
#Usage ex: bash findRBH.sh blast.outfmt6 blast_reciprocal.outfmt6

#Input query blast results file
queryPath="/Users/la424/Aquadro_lab/fasta_files_blast_database/blast_outputs/blast.outfmt6"
#Input DB reciprocal blast results file
dbPath="/Users/la424/Aquadro_lab/fasta_files_blast_database/blast_outputs/blast_reciprocal.outfmt6"
​
#Final output files
outFileRBH="blast_RBH.txt"
outFileSummary="blast_RBH_summary.txt"

#Add headers to output RBH files
echo "queryHit,dbHit" > $outFileRBH
echo "queryHits,dbHits,bestHits" > $outFileSummary​

#Output start status message
echo "Recording RBH..."
​
#Loop over query blast results
while IFS=$'\t' read -r f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12
do
	#Determine RBH to DB blast results
	if grep -q "$f2"$'\t'"$f1"$'\t' $dbPath; then #RBH
		echo "$f1,$f2" >> $outFileRBH
	fi
done < $queryPath

#Output summary of RBH
queryHits=$(wc -l "$queryPath" | cut -d ' ' -f 1)
dbHits=$(wc -l "$dbPath" | cut -d ' ' -f 1)
bestHits=$(($(wc -l "$outFileRBH" | cut -d ' ' -f 1)-1))
echo "$queryHits","$dbHits","$bestHits" >> $outFileSummary
​
#Output end status message
echo "Finished recording RBH!"